PROMETHEUS_HOST: "http://prometheus:9090"
K8S_MASTER: ""
GRAFANA_AGG_TEMPLATE: "template/Aggregation.tmpl"
AGGREGATION_DURATION: 6h
HISTORY_AGGREGATION_DURATION: 90d
HISTORY_WAVE_THRESHOLD: 40
HISTORY_REBOUND_THRESHOLD: 10
SMOOTH_WAVE_THRESHOLD: 10